/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CONTROL.ControlFuncionario;
import CONTROL.Principal;

/**
 *
 * @author Alexandre Freitas
 */
public class FormFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form FormFuncionario
     */
    public FormFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnConfirmarFuncionario = new javax.swing.JButton();
        btnCancelarFuncionario = new javax.swing.JButton();
        btnSairFuncionario = new javax.swing.JButton();
        cbxDadosPessoaisFuncionario = new javax.swing.JComboBox<String>();
        cbxUsuarioFuncionario = new javax.swing.JComboBox();

        setMaximumSize(new java.awt.Dimension(575, 250));
        setMinimumSize(new java.awt.Dimension(575, 250));
        setPreferredSize(new java.awt.Dimension(575, 250));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Dados Pessoais");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 50, 90, 14);

        jLabel2.setText("Usuario");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 100, 270, 14);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setText("Funcionario");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 10, 180, 30);

        btnConfirmarFuncionario.setText("Confirmar");
        btnConfirmarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmarFuncionario);
        btnConfirmarFuncionario.setBounds(420, 170, 100, 23);

        btnCancelarFuncionario.setText("Cancelar");
        btnCancelarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarFuncionario);
        btnCancelarFuncionario.setBounds(50, 170, 90, 23);

        btnSairFuncionario.setText("Sair");
        btnSairFuncionario.setName(""); // NOI18N
        btnSairFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnSairFuncionario);
        btnSairFuncionario.setBounds(240, 170, 70, 23);

        getContentPane().add(cbxDadosPessoaisFuncionario);
        cbxDadosPessoaisFuncionario.setBounds(10, 70, 540, 20);

        getContentPane().add(cbxUsuarioFuncionario);
        cbxUsuarioFuncionario.setBounds(10, 120, 540, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarFuncionarioActionPerformed
        Principal.mostrarTelaInicio();
        ControlFuncionario.limparCampos();
    }//GEN-LAST:event_btnCancelarFuncionarioActionPerformed

    private void btnSairFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairFuncionarioActionPerformed
        Principal.mostrarTelaInicio();
        ControlFuncionario.limparCampos();
    }//GEN-LAST:event_btnSairFuncionarioActionPerformed

    private void btnConfirmarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarFuncionarioActionPerformed
        if(ControlFuncionario.editando == false)
            ControlFuncionario.cadastrar();
        else
            ControlFuncionario.editar(ControlFuncionario.idAux);
    }//GEN-LAST:event_btnConfirmarFuncionarioActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Principal.mostrarTelaInicio();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarFuncionario;
    public javax.swing.JButton btnConfirmarFuncionario;
    public javax.swing.JButton btnSairFuncionario;
    public static javax.swing.JComboBox<String> cbxDadosPessoaisFuncionario;
    public static javax.swing.JComboBox cbxUsuarioFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
