/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CONTROL.ControlUsuario;
import CONTROL.Principal;

/**
 *
 * @author 20161STADS0039
 */
public class FormUsuario extends javax.swing.JFrame {

    /**
     * Creates new form FormUsuario
     */
    public FormUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtLoginUsuario = new javax.swing.JTextField();
        txtSenhaUsuario = new javax.swing.JTextField();
        cbxTipoUsuario = new javax.swing.JComboBox<String>();
        btnCancelarUsuario = new javax.swing.JButton();
        btnSairUsuario = new javax.swing.JButton();
        btnConfirmarUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(575, 285));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Login");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 50, 50, 14);

        jLabel3.setText("Senha");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 100, 70, 14);

        jLabel5.setText("Tipo de Usuario");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 150, 100, 14);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setText("Usuário");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 10, 290, 30);
        getContentPane().add(txtLoginUsuario);
        txtLoginUsuario.setBounds(10, 70, 550, 20);
        getContentPane().add(txtSenhaUsuario);
        txtSenhaUsuario.setBounds(10, 120, 550, 20);

        cbxTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um...", "Funcionário", "Gerente", "Administrador" }));
        getContentPane().add(cbxTipoUsuario);
        cbxTipoUsuario.setBounds(10, 170, 550, 20);

        btnCancelarUsuario.setText("Cancelar");
        btnCancelarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarUsuario);
        btnCancelarUsuario.setBounds(50, 220, 90, 23);

        btnSairUsuario.setText("Sair");
        btnSairUsuario.setName(""); // NOI18N
        btnSairUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnSairUsuario);
        btnSairUsuario.setBounds(240, 220, 70, 23);

        btnConfirmarUsuario.setText("Confirmar");
        btnConfirmarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmarUsuario);
        btnConfirmarUsuario.setBounds(420, 220, 100, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarUsuarioActionPerformed
        Principal.mostrarTelaInicio();
        ControlUsuario.limparCampos();
    }//GEN-LAST:event_btnCancelarUsuarioActionPerformed

    private void btnSairUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairUsuarioActionPerformed
        Principal.mostrarTelaInicio();
        ControlUsuario.limparCampos();
    }//GEN-LAST:event_btnSairUsuarioActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Principal.mostrarTelaInicio();
    }//GEN-LAST:event_formWindowClosing

    private void btnConfirmarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarUsuarioActionPerformed
        if(ControlUsuario.editando == false)
            ControlUsuario.cadastrar();
        else
            ControlUsuario.editar(ControlUsuario.idAux);
    }//GEN-LAST:event_btnConfirmarUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarUsuario;
    public javax.swing.JButton btnConfirmarUsuario;
    public javax.swing.JButton btnSairUsuario;
    public static javax.swing.JComboBox<String> cbxTipoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JTextField txtLoginUsuario;
    public static javax.swing.JTextField txtSenhaUsuario;
    // End of variables declaration//GEN-END:variables
}
