/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CONTROL.ControlItensPedido;
import CONTROL.ControlPedido;
import CONTROL.Principal;

/**
 *
 * @author Victor
 */
public class FormItensPedido extends javax.swing.JFrame {

    /**
     * Creates new form FormItensPedido
     */
    public FormItensPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCancelarItensPedido = new javax.swing.JButton();
        btnConfirmarItensPedido = new javax.swing.JButton();
        btnSairItensPedido = new javax.swing.JButton();
        cbxPedidoItensPedido = new javax.swing.JComboBox<String>();
        cbxProdutoItensPedido = new javax.swing.JComboBox<String>();
        txtQuantidadeItensPedido = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(575, 300));
        setMinimumSize(new java.awt.Dimension(575, 300));
        setPreferredSize(new java.awt.Dimension(575, 300));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel3.setText("Pedido (*)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 51, 170, 20);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setText("Item do Pedido");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 11, 241, 29);

        jLabel4.setText("Campos Obrigatórios  (*)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(390, 31, 160, 14);

        jLabel5.setText("Produto (*)");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 110, 170, 20);

        jLabel1.setText("Quantidade (*)");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 170, 170, 14);

        btnCancelarItensPedido.setText("Cancelar");
        btnCancelarItensPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarItensPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarItensPedido);
        btnCancelarItensPedido.setBounds(50, 230, 90, 23);

        btnConfirmarItensPedido.setText("Confirmar");
        btnConfirmarItensPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarItensPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmarItensPedido);
        btnConfirmarItensPedido.setBounds(420, 230, 100, 23);

        btnSairItensPedido.setText("Sair");
        btnSairItensPedido.setName(""); // NOI18N
        btnSairItensPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairItensPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSairItensPedido);
        btnSairItensPedido.setBounds(240, 230, 70, 23);

        getContentPane().add(cbxPedidoItensPedido);
        cbxPedidoItensPedido.setBounds(10, 72, 540, 20);

        getContentPane().add(cbxProdutoItensPedido);
        cbxProdutoItensPedido.setBounds(10, 130, 540, 20);
        getContentPane().add(txtQuantidadeItensPedido);
        txtQuantidadeItensPedido.setBounds(10, 190, 540, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarItensPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarItensPedidoActionPerformed
        Principal.mostrarTelaInicio();
                ControlItensPedido.limparCampos();
    }//GEN-LAST:event_btnCancelarItensPedidoActionPerformed

    private void btnConfirmarItensPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarItensPedidoActionPerformed
                if(ControlItensPedido.editando == false)
                    ControlItensPedido.cadastrar();   
                else
                    ControlItensPedido.editar(ControlItensPedido.idAux);
    }//GEN-LAST:event_btnConfirmarItensPedidoActionPerformed

    private void btnSairItensPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairItensPedidoActionPerformed
        Principal.mostrarTelaInicio();
                ControlItensPedido.limparCampos();
    }//GEN-LAST:event_btnSairItensPedidoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Principal.mostrarTelaInicio();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarItensPedido;
    public javax.swing.JButton btnConfirmarItensPedido;
    public javax.swing.JButton btnSairItensPedido;
    public javax.swing.JComboBox<String> cbxPedidoItensPedido;
    public javax.swing.JComboBox<String> cbxProdutoItensPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JTextField txtQuantidadeItensPedido;
    // End of variables declaration//GEN-END:variables
}
