/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CONTROL.ControlServico;
import CONTROL.Principal;

/**
 *
 * @author 20161STADS0039
 */
public class FormServicoFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form FormServicoFornecedor
     */
    public FormServicoFornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNomeServico = new javax.swing.JTextField();
        txtValorServico = new javax.swing.JTextField();
        cbxFornecedorServico = new javax.swing.JComboBox<String>();
        btnCancelarServico = new javax.swing.JButton();
        btnSairServico = new javax.swing.JButton();
        btnConfirmarServico = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(575, 300));
        setMinimumSize(new java.awt.Dimension(575, 300));
        setPreferredSize(new java.awt.Dimension(575, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Serviço");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 50, 50, 14);

        jLabel3.setText("Fornecedor");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 100, 70, 14);

        jLabel5.setText("Valor");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 150, 60, 14);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setText("Serviço por Fornecedor");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 10, 290, 30);
        getContentPane().add(txtNomeServico);
        txtNomeServico.setBounds(10, 70, 540, 20);
        getContentPane().add(txtValorServico);
        txtValorServico.setBounds(10, 170, 540, 20);

        getContentPane().add(cbxFornecedorServico);
        cbxFornecedorServico.setBounds(10, 120, 540, 20);

        btnCancelarServico.setText("Cancelar");
        btnCancelarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarServicoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarServico);
        btnCancelarServico.setBounds(50, 220, 90, 23);

        btnSairServico.setText("Sair");
        btnSairServico.setName(""); // NOI18N
        btnSairServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairServicoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSairServico);
        btnSairServico.setBounds(240, 220, 70, 23);

        btnConfirmarServico.setText("Confirmar");
        btnConfirmarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarServicoActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmarServico);
        btnConfirmarServico.setBounds(420, 220, 100, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarServicoActionPerformed
        Principal.mostrarTelaInicio();
    }//GEN-LAST:event_btnCancelarServicoActionPerformed

    private void btnSairServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairServicoActionPerformed
        Principal.mostrarTelaInicio();
    }//GEN-LAST:event_btnSairServicoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Principal.mostrarTelaInicio();
    }//GEN-LAST:event_formWindowClosing

    private void btnConfirmarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarServicoActionPerformed
        if(ControlServico.editando == false)
            ControlServico.cadastrar();
        else
            ControlServico.editar(ControlServico.idAux);
    }//GEN-LAST:event_btnConfirmarServicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarServico;
    public javax.swing.JButton btnConfirmarServico;
    public javax.swing.JButton btnSairServico;
    public static javax.swing.JComboBox<String> cbxFornecedorServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JTextField txtNomeServico;
    public static javax.swing.JTextField txtValorServico;
    // End of variables declaration//GEN-END:variables
}
