/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CONTROL.ControlEndereco;
import CONTROL.Principal;

/**
 *
 * @author 20161STADS0039
 */
public class FormEndereco extends javax.swing.JFrame {

    /**
     * Creates new form FormEndereco
     */
    public FormEndereco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLogradouroEndereco = new javax.swing.JTextField();
        txtNumeroEndereco = new javax.swing.JTextField();
        txtBairroEndereco = new javax.swing.JTextField();
        txtCidadeEndereco = new javax.swing.JTextField();
        cbxEstadosEndereco = new javax.swing.JComboBox();
        txtCEPEndereco = new javax.swing.JTextField();
        txtComplementoEndereco = new javax.swing.JTextField();
        txtReferenciaEndereco = new javax.swing.JTextField();
        btnCancelarEndereco = new javax.swing.JButton();
        btnSairEndereco = new javax.swing.JButton();
        btnConfirmarEndereco = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(575, 440));
        setMinimumSize(new java.awt.Dimension(575, 440));
        setPreferredSize(new java.awt.Dimension(575, 440));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel7.setText("Logradouro (*)");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 51, 90, 14);

        jLabel8.setText("CEP (*)");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(230, 201, 70, 14);

        jLabel9.setText("Número");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 101, 50, 14);

        jLabel10.setText("Bairro (*)");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(180, 101, 100, 14);

        jLabel11.setText("Cidade (*)");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 151, 90, 14);

        jLabel12.setText("Estado (*)");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 201, 90, 14);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel14.setText("Endereço");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 11, 110, 34);

        jLabel1.setText("Complemento");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 252, 100, 14);

        jLabel2.setText("Referência");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 303, 90, 14);
        getContentPane().add(txtLogradouroEndereco);
        txtLogradouroEndereco.setBounds(10, 71, 540, 20);
        getContentPane().add(txtNumeroEndereco);
        txtNumeroEndereco.setBounds(10, 121, 160, 20);
        getContentPane().add(txtBairroEndereco);
        txtBairroEndereco.setBounds(180, 121, 370, 20);
        getContentPane().add(txtCidadeEndereco);
        txtCidadeEndereco.setBounds(10, 171, 540, 20);

        cbxEstadosEndereco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um Estado...", "AC - Acre", "AL - Alagoas", "AP - Amapá", "AM - Amazonas", "BA - Bahia", "CE - Ceará", "DF - Distrito Federal", "ES - Espírito Santo", "GO - Goiás", "MA - Maranhão", "MT - Mato Grosso", "MS - Mato Grosso do Sul", "MG - Minas Gerais", "PA - Pará", "PB - Paraíba", "PR - Paraná", "PE - Pernambuco", "PI - Piauí", "RJ - Rio de Janeiro", "RN - Rio Grande do Norte", "RS - Rio Grande do Sul", "RO - Rondônia", "RR - Roraima", "SC - Santa Catarina", "SP - São Paulo", "SE - Sergipe", "TO - Tocantins" }));
        getContentPane().add(cbxEstadosEndereco);
        cbxEstadosEndereco.setBounds(10, 221, 210, 20);
        getContentPane().add(txtCEPEndereco);
        txtCEPEndereco.setBounds(230, 221, 320, 20);
        getContentPane().add(txtComplementoEndereco);
        txtComplementoEndereco.setBounds(10, 270, 540, 20);
        getContentPane().add(txtReferenciaEndereco);
        txtReferenciaEndereco.setBounds(10, 323, 540, 20);

        btnCancelarEndereco.setText("Cancelar");
        btnCancelarEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarEndereco);
        btnCancelarEndereco.setBounds(40, 370, 90, 23);

        btnSairEndereco.setText("Sair");
        btnSairEndereco.setName(""); // NOI18N
        btnSairEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSairEndereco);
        btnSairEndereco.setBounds(230, 370, 70, 23);

        btnConfirmarEndereco.setText("Confirmar");
        btnConfirmarEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmarEndereco);
        btnConfirmarEndereco.setBounds(410, 370, 100, 23);

        jLabel3.setText("Campos Obrigatórios  (*)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(390, 30, 160, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEnderecoActionPerformed
        Principal.mostrarTelaInicio();
        ControlEndereco.limparCampos();
    }//GEN-LAST:event_btnCancelarEnderecoActionPerformed

    private void btnSairEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairEnderecoActionPerformed
        Principal.mostrarTelaInicio();
        ControlEndereco.limparCampos();
    }//GEN-LAST:event_btnSairEnderecoActionPerformed

    private void btnConfirmarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarEnderecoActionPerformed
        if(ControlEndereco.editando == false)
            ControlEndereco.cadastrar();
        else
            ControlEndereco.editar(ControlEndereco.idAux);
    }//GEN-LAST:event_btnConfirmarEnderecoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Principal.mostrarTelaInicio();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarEndereco;
    public javax.swing.JButton btnConfirmarEndereco;
    public javax.swing.JButton btnSairEndereco;
    public static javax.swing.JComboBox cbxEstadosEndereco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JTextField txtBairroEndereco;
    public static javax.swing.JTextField txtCEPEndereco;
    public static javax.swing.JTextField txtCidadeEndereco;
    public static javax.swing.JTextField txtComplementoEndereco;
    public static javax.swing.JTextField txtLogradouroEndereco;
    public static javax.swing.JTextField txtNumeroEndereco;
    public static javax.swing.JTextField txtReferenciaEndereco;
    // End of variables declaration//GEN-END:variables
}
