/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CONTROL.ControlPedido;
import CONTROL.Principal;

/**
 *
 * @author Victor
 */
public class FormPedido extends javax.swing.JFrame {

    /**
     * Creates new form FormPedido
     */
    public FormPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCancelarPedido = new javax.swing.JButton();
        btnConfirmarPedido = new javax.swing.JButton();
        btnSairPedido = new javax.swing.JButton();
        cbxClientePedido = new javax.swing.JComboBox<String>();
        cbxStatusPedido = new javax.swing.JComboBox<String>();

        setMinimumSize(new java.awt.Dimension(575, 240));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel3.setText("Cliente (*)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 51, 170, 20);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setText("Pedido");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 11, 241, 29);

        jLabel4.setText("Campos Obrigatórios  (*)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(390, 31, 160, 14);

        jLabel5.setText("Status (*)");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 110, 170, 20);

        btnCancelarPedido.setText("Cancelar");
        btnCancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarPedido);
        btnCancelarPedido.setBounds(40, 170, 90, 23);

        btnConfirmarPedido.setText("Confirmar");
        btnConfirmarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmarPedido);
        btnConfirmarPedido.setBounds(420, 170, 100, 23);

        btnSairPedido.setText("Sair");
        btnSairPedido.setName(""); // NOI18N
        btnSairPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSairPedido);
        btnSairPedido.setBounds(250, 170, 70, 23);

        getContentPane().add(cbxClientePedido);
        cbxClientePedido.setBounds(10, 72, 540, 20);

        getContentPane().add(cbxStatusPedido);
        cbxStatusPedido.setBounds(10, 130, 540, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPedidoActionPerformed
        Principal.mostrarTelaInicio();
                ControlPedido.limparCampos();
    }//GEN-LAST:event_btnCancelarPedidoActionPerformed

    private void btnConfirmarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPedidoActionPerformed
                if(ControlPedido.editando == false)
                    ControlPedido.cadastrar();
                else
                    ControlPedido.editar(ControlPedido.idAux);
    }//GEN-LAST:event_btnConfirmarPedidoActionPerformed

    private void btnSairPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairPedidoActionPerformed
        Principal.mostrarTelaInicio();
                ControlPedido.limparCampos();
    }//GEN-LAST:event_btnSairPedidoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Principal.mostrarTelaInicio();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarPedido;
    public javax.swing.JButton btnConfirmarPedido;
    public javax.swing.JButton btnSairPedido;
    public javax.swing.JComboBox<String> cbxClientePedido;
    public javax.swing.JComboBox<String> cbxStatusPedido;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
