/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CONTROL.ControlPartesProduto;
import CONTROL.Principal;

/**
 *
 * @author Victor
 */
public class FormPartesProduto extends javax.swing.JFrame {

    /**
     * Creates new form FormPartesProduto
     */
    public FormPartesProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCancelarPartesProduto = new javax.swing.JButton();
        btnConfirmarPartesProduto = new javax.swing.JButton();
        btnSairPartesProduto = new javax.swing.JButton();
        cbxPartePartesProduto = new javax.swing.JComboBox<>();
        cbxProdutoPartesProduto = new javax.swing.JComboBox<>();

        setMinimumSize(new java.awt.Dimension(575, 240));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel3.setText("Parte (*)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 51, 170, 20);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setText("Partes de Produto");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 11, 241, 29);

        jLabel4.setText("Campos Obrigatórios  (*)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(390, 31, 160, 14);

        jLabel5.setText("Produto (*)");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 110, 170, 20);

        btnCancelarPartesProduto.setText("Cancelar");
        btnCancelarPartesProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPartesProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarPartesProduto);
        btnCancelarPartesProduto.setBounds(40, 170, 90, 23);

        btnConfirmarPartesProduto.setText("Confirmar");
        btnConfirmarPartesProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarPartesProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmarPartesProduto);
        btnConfirmarPartesProduto.setBounds(410, 170, 100, 23);

        btnSairPartesProduto.setText("Sair");
        btnSairPartesProduto.setName(""); // NOI18N
        btnSairPartesProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairPartesProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSairPartesProduto);
        btnSairPartesProduto.setBounds(230, 170, 70, 23);

        getContentPane().add(cbxPartePartesProduto);
        cbxPartePartesProduto.setBounds(10, 72, 540, 20);

        getContentPane().add(cbxProdutoPartesProduto);
        cbxProdutoPartesProduto.setBounds(10, 130, 540, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarPartesProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPartesProdutoActionPerformed
        Principal.mostrarTelaInicio();
                ControlPartesProduto.limparCampos();
    }//GEN-LAST:event_btnCancelarPartesProdutoActionPerformed

    private void btnConfirmarPartesProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPartesProdutoActionPerformed
                if(ControlPartesProduto.editando == false)
                    ControlPartesProduto.cadastrar();
                else
                    ControlPartesProduto.editar(ControlPartesProduto.idAux);
    }//GEN-LAST:event_btnConfirmarPartesProdutoActionPerformed

    private void btnSairPartesProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairPartesProdutoActionPerformed
        Principal.mostrarTelaInicio();
                ControlPartesProduto.limparCampos();
    }//GEN-LAST:event_btnSairPartesProdutoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Principal.mostrarTelaInicio();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarPartesProduto;
    public javax.swing.JButton btnConfirmarPartesProduto;
    public javax.swing.JButton btnSairPartesProduto;
    public javax.swing.JComboBox<String> cbxPartePartesProduto;
    public javax.swing.JComboBox<String> cbxProdutoPartesProduto;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
