/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CONTROL.ControlDados;
import CONTROL.Principal;

/**
 *
 * @author Alexandre Freitas
 */
public class FormDadosPessoais extends javax.swing.JFrame {

    /**
     * Creates new form FormDadosPessoais
     */
    public FormDadosPessoais() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNomeDados = new javax.swing.JTextField();
        txtEmailDados = new javax.swing.JTextField();
        txtTelefoneDados = new javax.swing.JTextField();
        txtCelularDados = new javax.swing.JTextField();
        cbxEnderecoDados = new javax.swing.JComboBox<>();
        btnCancelarDados = new javax.swing.JButton();
        btnSairDados = new javax.swing.JButton();
        btnConfirmarDados = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(575, 350));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                chamarInicio(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Nome (*)");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 50, 50, 20);

        jLabel3.setText("Endereço (*)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 200, 70, 20);

        jLabel4.setText("E-mail");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 100, 50, 20);

        jLabel5.setText("Fixo");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 150, 60, 20);

        jLabel6.setText("Celular");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(290, 150, 50, 20);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setText("Dados");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 10, 210, 29);

        jLabel7.setText("Campos Obrigatórios  (*)");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(390, 30, 160, 14);
        getContentPane().add(txtNomeDados);
        txtNomeDados.setBounds(10, 70, 540, 20);
        getContentPane().add(txtEmailDados);
        txtEmailDados.setBounds(10, 120, 540, 20);
        getContentPane().add(txtTelefoneDados);
        txtTelefoneDados.setBounds(10, 170, 270, 20);
        getContentPane().add(txtCelularDados);
        txtCelularDados.setBounds(290, 170, 260, 20);
        getContentPane().add(cbxEnderecoDados);
        cbxEnderecoDados.setBounds(10, 220, 540, 20);

        btnCancelarDados.setText("Cancelar");
        btnCancelarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarDadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarDados);
        btnCancelarDados.setBounds(50, 270, 90, 23);

        btnSairDados.setText("Sair");
        btnSairDados.setName(""); // NOI18N
        btnSairDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairDadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnSairDados);
        btnSairDados.setBounds(240, 270, 70, 23);

        btnConfirmarDados.setText("Confirmar");
        btnConfirmarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarDadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmarDados);
        btnConfirmarDados.setBounds(420, 270, 100, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarDadosActionPerformed
        Principal.mostrarTelaInicio();
        ControlDados.limparCampos();
    }//GEN-LAST:event_btnCancelarDadosActionPerformed

    private void btnSairDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairDadosActionPerformed
        Principal.mostrarTelaInicio();
        ControlDados.limparCampos();
    }//GEN-LAST:event_btnSairDadosActionPerformed

    private void chamarInicio(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_chamarInicio
        Principal.mostrarTelaInicio();
    }//GEN-LAST:event_chamarInicio

    private void btnConfirmarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarDadosActionPerformed
        if(ControlDados.editando == false)
            ControlDados.cadastrar();
        else
            ControlDados.editar(ControlDados.idAux);
    }//GEN-LAST:event_btnConfirmarDadosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarDados;
    public javax.swing.JButton btnConfirmarDados;
    public javax.swing.JButton btnSairDados;
    public static javax.swing.JComboBox<String> cbxEnderecoDados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JTextField txtCelularDados;
    public static javax.swing.JTextField txtEmailDados;
    public static javax.swing.JTextField txtNomeDados;
    public static javax.swing.JTextField txtTelefoneDados;
    // End of variables declaration//GEN-END:variables
}
