/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CONTROL.ControlEstoque;
import CONTROL.Principal;

/**
 *
 * @author Victor
 */
public class FormEstoque extends javax.swing.JFrame {

    /**
     * Creates new form FormEstoque
     */
    public FormEstoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbxEnderecoEstoque = new javax.swing.JComboBox<String>();
        btnCancelarEstoque = new javax.swing.JButton();
        btnSairEstoque = new javax.swing.JButton();
        btnConfirmarEstoque = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(575, 200));
        setMinimumSize(new java.awt.Dimension(575, 200));
        setPreferredSize(new java.awt.Dimension(575, 200));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel3.setText("Endereço (*)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 51, 170, 20);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setText("Estoque");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 11, 170, 29);

        jLabel4.setText("Campos Obrigatórios  (*)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(390, 31, 160, 14);

        getContentPane().add(cbxEnderecoEstoque);
        cbxEnderecoEstoque.setBounds(10, 71, 540, 20);

        btnCancelarEstoque.setText("Cancelar");
        btnCancelarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEstoqueActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarEstoque);
        btnCancelarEstoque.setBounds(50, 121, 90, 23);

        btnSairEstoque.setText("Sair");
        btnSairEstoque.setName(""); // NOI18N
        btnSairEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairEstoqueActionPerformed(evt);
            }
        });
        getContentPane().add(btnSairEstoque);
        btnSairEstoque.setBounds(240, 121, 70, 23);

        btnConfirmarEstoque.setText("Confirmar");
        btnConfirmarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarEstoqueActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmarEstoque);
        btnConfirmarEstoque.setBounds(420, 121, 100, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEstoqueActionPerformed
        Principal.mostrarTelaInicio();
            ControlEstoque.limparCampos();
    }//GEN-LAST:event_btnCancelarEstoqueActionPerformed

    private void btnSairEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairEstoqueActionPerformed
        Principal.mostrarTelaInicio();
            ControlEstoque.limparCampos();
    }//GEN-LAST:event_btnSairEstoqueActionPerformed

    private void btnConfirmarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarEstoqueActionPerformed
        if(ControlEstoque.editando == false)
            ControlEstoque.cadastrar();
        else
            ControlEstoque.editar(ControlEstoque.idAux);
    }//GEN-LAST:event_btnConfirmarEstoqueActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Principal.mostrarTelaInicio();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarEstoque;
    public javax.swing.JButton btnConfirmarEstoque;
    public javax.swing.JButton btnSairEstoque;
    public static javax.swing.JComboBox<String> cbxEnderecoEstoque;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
