/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CONTROL.ControlProduto;
import CONTROL.Principal;

/**
 *
 * @author Victor
 */
public class FormProduto extends javax.swing.JFrame {

    /**
     * Creates new form FormProduto
     */
    public FormProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNomeProduto = new javax.swing.JTextField();
        txtPrecoProduto = new javax.swing.JTextField();
        cbxGeneroProduto = new javax.swing.JComboBox<String>();
        cbCustomizavelProduto = new javax.swing.JCheckBox();
        cbxTipoProduto = new javax.swing.JComboBox<String>();
        btnCancelarProduto = new javax.swing.JButton();
        btnConfirmarProduto = new javax.swing.JButton();
        btnSairProduto = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(575, 380));
        setMinimumSize(new java.awt.Dimension(575, 380));
        setPreferredSize(new java.awt.Dimension(575, 380));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel3.setText("Nome (*)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 51, 170, 20);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setText("Produto");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 11, 160, 29);

        jLabel4.setText("Campos Obrigatórios  (*)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(390, 31, 160, 14);

        jLabel5.setText("Preço (*)");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 110, 170, 20);

        jLabel1.setText("Gênero");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 170, 110, 14);

        jLabel2.setText("Opcional");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 170, 110, 14);

        jLabel6.setText("Tipo (*)");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 230, 90, 14);
        getContentPane().add(txtNomeProduto);
        txtNomeProduto.setBounds(10, 71, 540, 20);
        getContentPane().add(txtPrecoProduto);
        txtPrecoProduto.setBounds(10, 130, 540, 20);

        cbxGeneroProduto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um...", "Unissex", "Masculino", "Feminino" }));
        getContentPane().add(cbxGeneroProduto);
        cbxGeneroProduto.setBounds(10, 190, 290, 20);

        cbCustomizavelProduto.setText("Customizavel");
        getContentPane().add(cbCustomizavelProduto);
        cbCustomizavelProduto.setBounds(340, 190, 150, 23);

        getContentPane().add(cbxTipoProduto);
        cbxTipoProduto.setBounds(10, 250, 540, 20);

        btnCancelarProduto.setText("Cancelar");
        btnCancelarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarProduto);
        btnCancelarProduto.setBounds(50, 310, 90, 23);

        btnConfirmarProduto.setText("Confirmar");
        btnConfirmarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmarProduto);
        btnConfirmarProduto.setBounds(420, 310, 100, 23);

        btnSairProduto.setText("Sair");
        btnSairProduto.setName(""); // NOI18N
        btnSairProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSairProduto);
        btnSairProduto.setBounds(240, 310, 70, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarProdutoActionPerformed
        Principal.mostrarTelaInicio();
                ControlProduto.limparCampos();
    }//GEN-LAST:event_btnCancelarProdutoActionPerformed

    private void btnConfirmarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarProdutoActionPerformed
                if(ControlProduto.editando == false)
                    ControlProduto.cadastrar();
                else
                    ControlProduto.editar(ControlProduto.idAux);
    }//GEN-LAST:event_btnConfirmarProdutoActionPerformed

    private void btnSairProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairProdutoActionPerformed
        Principal.mostrarTelaInicio();
        ControlProduto.limparCampos();
    }//GEN-LAST:event_btnSairProdutoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Principal.mostrarTelaInicio();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarProduto;
    public javax.swing.JButton btnConfirmarProduto;
    public javax.swing.JButton btnSairProduto;
    public javax.swing.JCheckBox cbCustomizavelProduto;
    public javax.swing.JComboBox<String> cbxGeneroProduto;
    public javax.swing.JComboBox<String> cbxTipoProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JTextField txtNomeProduto;
    public static javax.swing.JTextField txtPrecoProduto;
    // End of variables declaration//GEN-END:variables
}
