/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CONTROL.ControlTipo;
import CONTROL.Principal;

/**
 *
 * @author Victor
 */
public class FormTipo extends javax.swing.JFrame {

    /**
     * Creates new form FormTipo
     */
    public FormTipo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNomeTipo = new javax.swing.JTextField();
        btnCancelarTipo = new javax.swing.JButton();
        btnConfirmarTipo = new javax.swing.JButton();
        btnSairTipo = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(575, 200));
        setMinimumSize(new java.awt.Dimension(575, 200));
        setPreferredSize(new java.awt.Dimension(575, 200));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel3.setText("Nome (*)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 51, 170, 20);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setText("Tipo do Produto");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 11, 209, 29);

        jLabel4.setText("Campos Obrigatórios  (*)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(390, 31, 160, 14);
        getContentPane().add(txtNomeTipo);
        txtNomeTipo.setBounds(10, 71, 540, 20);

        btnCancelarTipo.setText("Cancelar");
        btnCancelarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarTipoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarTipo);
        btnCancelarTipo.setBounds(50, 121, 90, 23);

        btnConfirmarTipo.setText("Confirmar");
        btnConfirmarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarTipoActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmarTipo);
        btnConfirmarTipo.setBounds(420, 121, 100, 23);

        btnSairTipo.setText("Sair");
        btnSairTipo.setName(""); // NOI18N
        btnSairTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairTipoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSairTipo);
        btnSairTipo.setBounds(240, 121, 70, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairTipoActionPerformed
        Principal.mostrarTelaInicio();
        ControlTipo.limparCampos();
    }//GEN-LAST:event_btnSairTipoActionPerformed

    private void btnConfirmarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarTipoActionPerformed
        if(ControlTipo.editando == false)
            ControlTipo.cadastrar();
        else
            ControlTipo.editar(ControlTipo.idAux);
    }//GEN-LAST:event_btnConfirmarTipoActionPerformed

    private void btnCancelarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarTipoActionPerformed
        Principal.mostrarTelaInicio();
        ControlTipo.limparCampos();
    }//GEN-LAST:event_btnCancelarTipoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Principal.mostrarTelaInicio();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarTipo;
    public javax.swing.JButton btnConfirmarTipo;
    public javax.swing.JButton btnSairTipo;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JTextField txtNomeTipo;
    // End of variables declaration//GEN-END:variables
}
