/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CONTROL.ControlFornecedor;
import CONTROL.Principal;

/**
 *
 * @author 20161STADS0039
 */
public class FormFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form FormFornecedor
     */
    public FormFornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbxDadosFornecedor = new javax.swing.JComboBox<>();
        btnCancelarFornecedor = new javax.swing.JButton();
        btnSairFornecedor = new javax.swing.JButton();
        btnConfirmarFornecedor = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(575, 200));
        setMinimumSize(new java.awt.Dimension(575, 200));
        setPreferredSize(new java.awt.Dimension(575, 200));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel3.setText("Dados da Empresa (*)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 50, 170, 20);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setText("Fornecedor");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 10, 170, 29);

        jLabel4.setText("Campos Obrigatórios  (*)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(390, 30, 160, 14);

        getContentPane().add(cbxDadosFornecedor);
        cbxDadosFornecedor.setBounds(10, 70, 540, 20);

        btnCancelarFornecedor.setText("Cancelar");
        btnCancelarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarFornecedorActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarFornecedor);
        btnCancelarFornecedor.setBounds(50, 120, 90, 23);

        btnSairFornecedor.setText("Sair");
        btnSairFornecedor.setName(""); // NOI18N
        btnSairFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairFornecedorActionPerformed(evt);
            }
        });
        getContentPane().add(btnSairFornecedor);
        btnSairFornecedor.setBounds(240, 120, 70, 23);

        btnConfirmarFornecedor.setText("Confirmar");
        btnConfirmarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarFornecedorActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmarFornecedor);
        btnConfirmarFornecedor.setBounds(420, 120, 100, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairFornecedorActionPerformed
        Principal.mostrarTelaInicio();
        ControlFornecedor.limparCampos();
    }//GEN-LAST:event_btnSairFornecedorActionPerformed

    private void btnCancelarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarFornecedorActionPerformed
        Principal.mostrarTelaInicio();
        ControlFornecedor.limparCampos();
    }//GEN-LAST:event_btnCancelarFornecedorActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Principal.mostrarTelaInicio();
    }//GEN-LAST:event_formWindowClosing

    private void btnConfirmarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarFornecedorActionPerformed
        if(ControlFornecedor.editando == false)
            ControlFornecedor.cadastrar();
        else
            ControlFornecedor.editar(ControlFornecedor.idAux);
    }//GEN-LAST:event_btnConfirmarFornecedorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarFornecedor;
    public javax.swing.JButton btnConfirmarFornecedor;
    public javax.swing.JButton btnSairFornecedor;
    public static javax.swing.JComboBox<String> cbxDadosFornecedor;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
