/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CONTROL.ControlProdutoEstoque;
import CONTROL.Principal;

/**
 *
 * @author Victor
 */
public class FormProdutosEstoque extends javax.swing.JFrame {

    /**
     * Creates new form FormProdutosEstoque
     */
    public FormProdutosEstoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCancelarProdutosEstoque = new javax.swing.JButton();
        btnConfirmarProdutosEstoque = new javax.swing.JButton();
        btnSairProdutosEstoque = new javax.swing.JButton();
        cbxEstoqueProdutosEstoque = new javax.swing.JComboBox<String>();
        cbxProdutoProdutosEstoque = new javax.swing.JComboBox<String>();
        txtQuantidadeProdutosEstoque = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(575, 300));
        setMinimumSize(new java.awt.Dimension(575, 300));
        setPreferredSize(new java.awt.Dimension(575, 300));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel3.setText("Estoque (*)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 51, 170, 20);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setText("Produto para Estoque");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 11, 290, 29);

        jLabel4.setText("Campos Obrigatórios  (*)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(390, 31, 160, 14);

        jLabel5.setText("Produto (*)");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 110, 170, 20);

        jLabel1.setText("Quantidade (*)");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 170, 170, 14);

        btnCancelarProdutosEstoque.setText("Cancelar");
        btnCancelarProdutosEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarProdutosEstoqueActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarProdutosEstoque);
        btnCancelarProdutosEstoque.setBounds(50, 230, 90, 23);

        btnConfirmarProdutosEstoque.setText("Confirmar");
        btnConfirmarProdutosEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarProdutosEstoqueActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmarProdutosEstoque);
        btnConfirmarProdutosEstoque.setBounds(420, 230, 100, 23);

        btnSairProdutosEstoque.setText("Sair");
        btnSairProdutosEstoque.setName(""); // NOI18N
        btnSairProdutosEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairProdutosEstoqueActionPerformed(evt);
            }
        });
        getContentPane().add(btnSairProdutosEstoque);
        btnSairProdutosEstoque.setBounds(240, 230, 70, 23);

        getContentPane().add(cbxEstoqueProdutosEstoque);
        cbxEstoqueProdutosEstoque.setBounds(10, 72, 540, 20);

        getContentPane().add(cbxProdutoProdutosEstoque);
        cbxProdutoProdutosEstoque.setBounds(10, 130, 540, 20);
        getContentPane().add(txtQuantidadeProdutosEstoque);
        txtQuantidadeProdutosEstoque.setBounds(10, 190, 540, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarProdutosEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarProdutosEstoqueActionPerformed
        Principal.mostrarTelaInicio();
                ControlProdutoEstoque.limparCampos();
    }//GEN-LAST:event_btnCancelarProdutosEstoqueActionPerformed

    private void btnConfirmarProdutosEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarProdutosEstoqueActionPerformed
                if(ControlProdutoEstoque.editando == false)
                    ControlProdutoEstoque.cadastrar();
                else
                    ControlProdutoEstoque.editar(ControlProdutoEstoque.idAux);
    }//GEN-LAST:event_btnConfirmarProdutosEstoqueActionPerformed

    private void btnSairProdutosEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairProdutosEstoqueActionPerformed
        Principal.mostrarTelaInicio();
                ControlProdutoEstoque.limparCampos();
    }//GEN-LAST:event_btnSairProdutosEstoqueActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Principal.mostrarTelaInicio();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarProdutosEstoque;
    public javax.swing.JButton btnConfirmarProdutosEstoque;
    public javax.swing.JButton btnSairProdutosEstoque;
    public javax.swing.JComboBox<String> cbxEstoqueProdutosEstoque;
    public javax.swing.JComboBox<String> cbxProdutoProdutosEstoque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JTextField txtQuantidadeProdutosEstoque;
    // End of variables declaration//GEN-END:variables
}
