/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CONTROL.ControlStatus;
import CONTROL.Principal;

/**
 *
 * @author Victor
 */
public class FormStatus extends javax.swing.JFrame {

    /**
     * Creates new form FormStatus
     */
    public FormStatus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNomeStatus = new javax.swing.JTextField();
        btnCancelarStatus = new javax.swing.JButton();
        btnConfirmarStatus = new javax.swing.JButton();
        btnSairStatus = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(575, 200));
        setMinimumSize(new java.awt.Dimension(575, 200));
        setPreferredSize(new java.awt.Dimension(575, 200));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel3.setText("Nome (*)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 51, 170, 20);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setText("Status de Pedido");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 11, 241, 29);

        jLabel4.setText("Campos Obrigatórios  (*)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(390, 31, 160, 14);
        getContentPane().add(txtNomeStatus);
        txtNomeStatus.setBounds(10, 71, 540, 20);

        btnCancelarStatus.setText("Cancelar");
        btnCancelarStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarStatusActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarStatus);
        btnCancelarStatus.setBounds(50, 121, 90, 23);

        btnConfirmarStatus.setText("Confirmar");
        btnConfirmarStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarStatusActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmarStatus);
        btnConfirmarStatus.setBounds(420, 121, 100, 23);

        btnSairStatus.setText("Sair");
        btnSairStatus.setName(""); // NOI18N
        btnSairStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairStatusActionPerformed(evt);
            }
        });
        getContentPane().add(btnSairStatus);
        btnSairStatus.setBounds(240, 121, 70, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarStatusActionPerformed
        Principal.mostrarTelaInicio();
                ControlStatus.limparCampos();
    }//GEN-LAST:event_btnCancelarStatusActionPerformed

    private void btnConfirmarStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarStatusActionPerformed
                if(ControlStatus.editando == false)
                    ControlStatus.cadastrar();
                else
                    ControlStatus.editar(ControlStatus.idAux);
    }//GEN-LAST:event_btnConfirmarStatusActionPerformed

    private void btnSairStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairStatusActionPerformed
        Principal.mostrarTelaInicio();
                ControlStatus.limparCampos();
    }//GEN-LAST:event_btnSairStatusActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Principal.mostrarTelaInicio();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarStatus;
    public javax.swing.JButton btnConfirmarStatus;
    public javax.swing.JButton btnSairStatus;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JTextField txtNomeStatus;
    // End of variables declaration//GEN-END:variables
}
